drop table if exists digest;
CREATE TABLE digest(
	serverid int NOT NULL,
	digestid int NOT NULL,
	digestname char(16) ,
	changeflag char(1) ,
	operflag char(1) ,
	usedflag char(1) ,
	macro varchar(32) ,
	biztype char(1) ,
	printorg varchar(1024) ,
	remark varchar(1024) ,
	PRIMARY KEY(
	digestid,
	serverid));

drop table if exists fundasset_hs;
CREATE TABLE fundasset_hs(
	serverid char(1) NOT NULL,
	orgid varchar(4) NOT NULL,
	custid bigint NOT NULL,
	fundid bigint NOT NULL,
	moneytype char(1) NOT NULL,
	fundlastbal numeric(20, 2) ,
	fundbal numeric(20, 2) ,
	fundbal_ch numeric(20, 2) ,
	fundsave numeric(20, 2) ,
	fundsave_ch numeric(20, 2) ,
	fundunsave numeric(20, 2) ,
	fundunsave_ch numeric(20, 2) ,
	fundloan numeric(20, 2) ,
	fundloan_ch numeric(20, 2) ,
	funddebt numeric(20, 2) ,
	funddebt_ch numeric(20, 2) ,
	funduncome numeric(20, 2) ,
	funduncome_ch numeric(20, 2) ,
	fundunpay numeric(20, 2) ,
	fundunpay_ch numeric(20, 2) ,
	fundadjust numeric(20, 2) ,
	fundadjust_ch numeric(20, 2) ,
	fundintr numeric(20, 2) ,
	fundintr_ch numeric(20, 2) ,
	fundaward numeric(20, 2) ,
	fundaward_ch numeric(20, 2) ,
	bankcode varchar(4) ,
	mktvalue numeric(20, 2) ,
	totalvalue numeric(20, 2) ,
	totalfe numeric(20, 2) ,
	nav numeric(12, 6) ,
	tjdate int ,
	remark varchar(64) ,
PRIMARY KEY
(
	fundid ,
	custid ,
	orgid ,
	moneytype ,
	serverid 
)
);

drop table if exists stkasset_hs;
CREATE TABLE stkasset_hs(
	serverid char(1) NOT NULL,
	orgid varchar(4) NOT NULL,
	custid bigint NOT NULL,
	fundid bigint NOT NULL,
	market char(1) NOT NULL,
	stkcode varchar(10) NOT NULL,
	stkbuyqty numeric(20, 2) ,
	stkbuyamt numeric(20, 2) ,
	stksaleqty numeric(20, 2) ,
	stksaleamt numeric(20, 2) ,
	stkztgrqty numeric(20, 2) ,
	stkztgramt numeric(20, 2) ,
	stkztgcqty numeric(20, 2) ,
	stkztgcamt numeric(20, 2) ,
	stkhgqty numeric(20, 2) ,
	stkhlamt numeric(20, 2) ,
	stkpgqty numeric(20, 2) ,
	stkpgamt numeric(20, 2) ,
	stkqty numeric(20, 2) ,
	stkqty_ch numeric(20, 2) ,
	stkpledge numeric(20, 2) ,
	stkdebt numeric(20, 2) ,
	stkloan numeric(20, 2) ,
	stkadjust numeric(20, 2) ,
	stkadjust_ch numeric(20, 2) ,
	stkprice numeric(12, 4) ,
	mktvalue numeric(20, 2) ,
	stkcost numeric(20, 2) ,
	stkcost_ch numeric(20, 2) ,
	syvalue numeric(20, 2) ,
	syvalue_ch numeric(20, 2) ,
	gyvalue numeric(20, 2) ,
	gyvalue_ch numeric(20, 2) ,
	lxsr numeric(20, 2) ,
	lxsr_ch numeric(20, 2) ,
	rzlx numeric(20, 2) ,
	rzlx_ch numeric(20, 2) ,
	rqlx numeric(20, 2) ,
	rqlx_ch numeric(20, 2) ,
	fee numeric(20, 2) ,
	fee_ch numeric(20, 2) ,
	qsyj numeric(20, 2) ,
	qsyj_ch numeric(20, 2) ,
	yhs numeric(20, 2) ,
	yhs_ch numeric(20, 2) ,
	ghf numeric(20, 2) ,
	ghf_ch numeric(20, 2) ,
	qtfee numeric(20, 2) ,
	qtfee_ch numeric(20, 2) ,
	lxs numeric(20, 2) ,
	lxs_ch numeric(20, 2) ,
	ltlx int NOT NULL,
	jtdate int ,
	remark varchar(128) ,
 PRIMARY KEY
(
	stkcode ,
	market ,
	ltlx ,
	fundid ,
	custid ,
	orgid ,
	serverid 
)
);

drop table if exists logasset_hs;
CREATE TABLE logasset_hs(
	serverid int NOT NULL,
	bizdate int NOT NULL,
	orderdate int ,
	sno int NOT NULL,
	relativesno int ,
	orgid char(4) ,
	custid bigint ,
	fundid bigint ,
	secuid varchar(32) ,
	moneytype char(1) ,
	digestid int ,
	market char(1) ,
	stkcode varchar(16) ,
	bankcode char(4) ,
	fundeffect numeric(20, 2) ,
	fundbal numeric(20, 2) ,
	stkeffect numeric(20, 2) ,
	stkbal numeric(20, 2) ,
	matchqty numeric(20, 2) ,
	matchamt numeric(20, 2) ,
	orderid varchar(10) ,
	matchprice numeric(9, 3) ,
	fee_jsxf numeric(20, 2) ,
	fee_sxf numeric(20, 2) ,
	fee_ghf numeric(20, 2) ,
	fee_yhs numeric(20, 2) ,
	feefront numeric(20, 2) ,
	operway char(1) ,
	ordersno int ,
	remark varchar(32) ,
	bsflag char(2) ,
	creditid char(1) ,
	creditflag char(1) ,
	ref_sno int ,
	ref_stkcode varchar(16) ,
	busintype int ,
	sett_status char(1) ,
	sett_remark varchar(128) ,
 PRIMARY KEY
(
	sno ,
	bizdate ,
	serverid 
)
);

drop table if exists stkprice;
CREATE TABLE stkprice(
	serverid int NOT NULL,
	bizdate int NOT NULL,
	market char(1) NOT NULL,
	stkcode char(8) NOT NULL,
	closeprice decimal(9, 3) NOT NULL,
	openprice decimal(9, 3) NOT NULL,
	lastprice decimal(9, 3) NOT NULL,
	highprice decimal(9, 3) NOT NULL,
	lowprice decimal(9, 3) NOT NULL,
	matchqty bigint NOT NULL,
	matchamt decimal(19, 2) NOT NULL,
	bondintr decimal(12, 8) NOT NULL,
	mtkcalflag char(1) NOT NULL
);

drop table if exists sysconfig;
CREATE TABLE sysconfig(
	iid int NOT NULL,
	cstep varchar(32) ,
	cstepname varchar(64) ,
	iskey char(1) ,
	threadnum int ,
	begtime varchar(32) ,
	endtime varchar(32) ,
	procticks int ,
	reccount int ,
	status char(1) ,
	remark varchar(256) ,
PRIMARY KEY (iid ));


drop table if exists stktrd
CREATE TABLE stktrd(
	serverid int NOT NULL,
	market char(1) NOT NULL,
	stkcode char(8) NOT NULL,
	linkstk char(8) NOT NULL,
	frzstk char(8) NOT NULL,
	stkname char(8) NOT NULL,
	stktype char(1) NOT NULL,
	trdid char(1) NOT NULL,
	moneytype char(1) NOT NULL,
	stopflag char(1) NOT NULL,
	bondintr decimal(12, 8) NOT NULL,
	intrdate int NOT NULL,
	maxrisevalue decimal(9, 3) NOT NULL,
	maxdownvalue decimal(9, 3) NOT NULL,
	fixprice decimal(9, 3) NOT NULL,
	limitpriceflag char(1) NOT NULL,
	defaultpricetype char(1) NOT NULL,
	maxriserate int NOT NULL,
	maxdownrate int NOT NULL,
	pt_ordertype varchar(8) NOT NULL,
	keepmode char(1) NOT NULL,
	ticketprice decimal(19, 2) NOT NULL,
	mtkcalflag char(1) NOT NULL,
	bsflag char(1) NOT NULL,
	cancelflag char(1) NOT NULL,
	priceflag char(1) NOT NULL,
	stkoverdraw char(1) NOT NULL,
	fundrealback char(1) NOT NULL,
	stockrealback char(1) NOT NULL,
	reserveprop varchar(128) NOT NULL,
	settlefundays int NOT NULL,
	settlestkdays int NOT NULL,
	funduseflag char(1) NOT NULL,
	stkusedflag char(1) NOT NULL,
	priceunit int NOT NULL,
	buyunit int NOT NULL,
	saleunit int NOT NULL,
	exchunit int NOT NULL,
	maxqty int NOT NULL,
	minqty int NOT NULL,
	firstdate int NOT NULL,
	upddate int NOT NULL,
	minbuyqty int NOT NULL,
	totalqty decimal(19, 2) NOT NULL,
	cirqty decimal(19, 2) NOT NULL,
	lastlimitday int NOT NULL,
	limitday int NOT NULL,
	quitdate int NOT NULL,
	memotext varchar(128) NOT NULL,
	chkmktvalueflag char(1) NOT NULL
);



/*
CREATE TABLE range(
	i int NOT NULL,
PRIMARY KEY
(
	i
));
*/
